# Node.js with React

# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- dev

pool:
  name: React Pipeline

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'

- script: |
    npm install
    npm test
    npm run build
  displayName: 'npm install -> npm test -> npm build'
  env:
    GENERATE_SOURCEMAP: $(GENERATE_SOURCEMAP)
    NODE_OPTIONS: $(NODE_OPTIONS)
    REACT_APP_PORT: $(REACT_APP_PORT)
    REACT_APP_DOMAIN: $(REACT_APP_DOMAIN)
    REACT_APP_SS_DOMAIN: $(REACT_APP_SS_DOMAIN)
    REACT_APP_RECAPTCHA_KEY: $(REACT_APP_RECAPTCHA_KEY)
    REACT_APP_GOOGLE_CLIENT_ID: $(REACT_APP_GOOGLE_CLIENT_ID)
    REACT_APP_STUN_SERVERS: $(REACT_APP_STUN_SERVERS)
    REACT_APP_TURN_SERVER_URL: $(REACT_APP_TURN_SERVER_URL)
    REACT_APP_TURN_SERVER_USERNAME: $(REACT_APP_TURN_SERVER_USERNAME)
    REACT_APP_TURN_SERVER_CREDENTIAL: $(REACT_APP_TURN_SERVER_CREDENTIAL)

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/build'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
    OverWrite: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'react-spa'