export const NEW_SUBSCRIBERS_RADIO_ID = 0;
export const EXPIRED_SUBSCRIBERS_RADIO_ID = 1;
export const BOTH_SUBSCRIBERS_RADIO_ID = 2;

export const DISCOUNT_MONTH_TYPE_RADIO_ID = 0;
export const FREE_TYPE_RADIO_ID = 1;
